version: '3.7'
services:
 apache:
  build: httpd/
  volumes:
   - ./DocumentRoot/:/usr/local/apache2/htdocs
  ports:
   - "6666:80"
  networks:
   - backend
   - frontend
  depends_on:
   - php   
   - mysql
 php:
  build: php/
  ports:
   - "9000:9000"  
  networks:
   - backend
  volumes:
   - ./DocumentRoot/:/var/www/html/
 mysql:
  build:
   context: ./mysql
   dockerfile: Dockerfile.debian
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: "mysql"
  ports:
   - "3306:3306"
  networks:
   - backend
  command: --default-authentication-plugin=mysql_native_password
networks:
 backend:
 frontend:
    
